//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ОКТМО-2014_final_my.xlsx")]
        public string OKTMOWorkbookPath {
            get {
                return ((string)(this["OKTMOWorkbookPath"]));
            }
            set {
                this["OKTMOWorkbookPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Справочники-2014_new.xlsx")]
        public string CatalogWorkbookPath {
            get {
                return ((string)(this["CatalogWorkbookPath"]));
            }
            set {
                this["CatalogWorkbookPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Справочники-2014_new.xlsx")]
        public string SourceListBySubjectWorkbookPath {
            get {
                return ((string)(this["SourceListBySubjectWorkbookPath"]));
            }
            set {
                this["SourceListBySubjectWorkbookPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\VGT.xlsx")]
        public string VGTWorkbookPath {
            get {
                return ((string)(this["VGTWorkbookPath"]));
            }
            set {
                this["VGTWorkbookPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("нас.пункты РФ")]
        public string OKTMOWorksheetName {
            get {
                return ((string)(this["OKTMOWorksheetName"]));
            }
            set {
                this["OKTMOWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("analytics")]
        public string CatalogWorksheetName {
            get {
                return ((string)(this["CatalogWorksheetName"]));
            }
            set {
                this["CatalogWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Список источников по регионам")]
        public string SubjectSourceWorksheetName {
            get {
                return ((string)(this["SubjectSourceWorksheetName"]));
            }
            set {
                this["SubjectSourceWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VGTWorksheetName {
            get {
                return ((string)(this["VGTWorksheetName"]));
            }
            set {
                this["VGTWorksheetName"] = value;
            }
        }
    }
}
